### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by idhun90** [uetchy/Polyglot#129] opened 2023-03-28 04:12 UTC
### Description

Not working cleanly since Ventura 13.3: translated popup view appears after dragging, then disappears immediately.

### To Reproduce

dragging

### What's My Browser Link

whatsmybrowser.org/b/L1XIJ

### Polyglot Version

3.4

**Comment by gingerbeardman** [comment] 2023-03-28 10:47
Duplicate of previous issue, #128

**Closed as completed** 2023-03-28 10:48 UTC
Labels: bug
