### ISSUE TITLE
Bug: The extension stop working on Ventura 13.3.1(a) and Safari 16.4 (18615.1.26.110.1)

### ISSUE THREAD

**Issue by ynivanov** [uetchy/Polyglot#140] opened 2023-05-30 06:33 UTC
### Description

When selecting the text the translation sometimes flashes for a second or never appears

### To Reproduce

Choose a web page. Select a text.

### What's My Browser Link

https://apps.apple.com/us/app/polyglot/id1471801525?mt=12

### Polyglot Version

3.4

### Additional context

Please be so kind if it is possible to fix it because Polyflot is the most comfortable app (extension) when browsing. Thanks in advance :)

**Comment by gingerbeardman** [comment] 2023-05-30 12:17
Duplicate of #128 which has a workaround.

**Closed as completed** 2023-05-30 12:18 UTC
Labels: bug
